### your site title here

title: pakddo.github.io


### let's use the minima theme (see https://github.com/jekyll/minima)

theme: jekyll-theme-minimal


### exclude the instructions / write-up in the README.md

exclude:
- README.md
